### ISSUE TITLE
Impossible to leave the "rotate object mode" when entered via the secondary button on a Wacom tablet pen.

### ISSUE THREAD

**Issue by hugovangalen** [Ultimaker/Cura#12554]
### Application Version

5.0.0

### Platform

Linux

### Printer

Ender3 Pro

### Reproduction steps

Use a Wacom tablet secondary button on the pen to rotate the object.

Stop pressing the secondary button to get out of rotate mode.

### Actual results

The object rotates, but it is impossible to escape rotate mode, bar restarting the application. Even using the 2nd mouse button which also enters/leaves rotate mode is useless at this point.

### Expected results

Leave rotate view mode when the secondary button on the pen is released. 

Note that this worked perfectly fine in 4.x versions.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No files to include. Nothing is logged when this occurs and this bug happens with an empty project.

**Comment by 3dHawwy** [comment]
Same problem here.  Mac, Wacom or touch pad.  Nothing works.

**Comment by Ghostkeeper** [comment]
What mouse command is your second button mapped to? If it is not the 2nd mouse button, this is expected behaviour.

**Comment by MariMakes** [comment]
Hey @hugovangalen,
Thanks for the report!

I literally dusted off my old Wacom Bamboo CTE 440 to verify your findings.
But it's not showing any unexpected behavior for me, perhaps because I'm on a windows device.

The issue however seems familiar to me. 
If you encounter it again, can you try to press Esc to leave Rotate Object Mode? 

In the meantime, I'll ask around to see if we have someone on the team with a tablet that can check what is going on.

**Comment by hugovangalen** [comment]
> The issue however seems familiar to me. If you encounter it again, can you try to press Esc to leave Rotate Object Mode?
> 
> In the meantime, I'll ask around to see if we have someone on the team with a tablet that can check what is going on.

I have just tested to verify: hitting Escape does not resolve the issue.

(I also tested this with the latest 5.1.0 version, by the way. Same thing happens there.)

**Comment by felderkwek** [comment]
I am having the same issue as well.

**Comment by Sjullep** [comment]
I have this problem too (MacOS 12.6 and a Wacom Intuos Pro). 
I had the same problem with the program Gyroflow. The solution de Gyroflow devs came with was updating QT version to 6.4.0. After that Gyroflow works fine here, so perhaps this is also the solution for the Cura 5.x problem?

**Comment by z0u** [comment]
Same here on Mac OS.

Cura 5.1.1
Wacom Pen & Touch CTH-490 version 1.0.0.0
Wacom drivers 6.3.46-1
Mac OS 12.6 / Intel

**Comment by MariMakes** [comment]
@GraafSybren mentioned that he might be able to supply a screen share of what he was running into.
Do you mind sharing it here?

**Comment by wchairy** [comment]
I'm having the same issue. Seriously, what the heck. I'm disabled and it's my only touch point into the system. I see that you're wanting a screen grab but of what something not working.

**Comment by GraafSybren** [comment]
I did a screen recording. Issue appears on 00:05
This bug seems to appear random after a while..
 there is no specific trick I have found to reproduce it.

https://user-images.githubusercontent.com/73584612/199455474-9020dabe-39f8-462a-aa87-7fc1691e3832.mov

**Comment by z0u** [comment]
Here's another screen recording, showing pen taps.

Black: Pen tip / left-click:
![image](https://user-images.githubusercontent.com/1408875/200985879-122e05ab-0ac0-46b3-944e-d3417fb0487c.png)

Green: Side button / right-click:
![image](https://user-images.githubusercontent.com/1408875/200985974-b95c7e5a-082c-4edc-b6e4-d44fcdeb82a1.png)

https://user-images.githubusercontent.com/1408875/200986819-57e78cb6-d9df-420e-92cb-bc1093f6420a.mov

Issue triggered at 0:24. Notice that, even though the button is released, it's still in rotate mode.

Tablet settings:

![image](https://user-images.githubusercontent.com/1408875/200985689-29fa3421-8b14-4a65-9ed1-5b6599f10e56.png)

**Comment by z0u** [comment]
Possible clue: it seems to happen most reliably after the pointer jumps to another part of the screen.

Both of the following recordings begin with a fresh instance of Cura.

Generally OK: not lifting the pen far from the tablet:

https://user-images.githubusercontent.com/1408875/200991668-0692c2a1-abca-4c1e-ac16-985fbd0c526a.mov

Generally fails: dragging after the pointer jumps:

https://user-images.githubusercontent.com/1408875/200991923-5ee8c86f-04f1-45c2-ad5f-05099cd29782.mov

**Comment by Braintoe** [comment]
I followed the forward from issue #13707 which suits the behaviour on my computer (Linux Mint with a Wacom Intuos Pro PTH-651 as a mouse replacement) better.

Things I can add to this:

- Cura (freshly installed as I am in the process of switching to a new 3D printer) registers movements of the pen but no clicks (i.e. tapping with the stylus or using a stylus button) at all
- if I put the stylus away and use the multitouch function of the tablet with my finger, it behaves normally
- Cura is not the only sofware affected by this bug, the Teamviewer remote access client shows exactly the same behaviour. This tells me it has to be some library (or such?) Cura and Teamviewer share
- all other programs I use behave as they should and recognise the stylus clicks in the same way as they do with a mouse.

**Comment by Braintoe** [comment]
Thanks to a little help from the xf86-input-wacom team, I could test the input with the `xinput test-xi2` terminal command. I compared a mouse click and a fingertip onto the tablet (both recognised by Cura) with a pen "click". This is what I got:

A click with multitouch (finger):

```
EVENT type 15 (RawButtonPress)
    device: 2 (10)
    detail: 1
    flags: 
    valuators:

EVENT type 16 (RawButtonRelease)
    device: 2 (10)
    detail: 1
    flags: 
    valuators:
```

A mouse click with deliberate motion while pressing the button to simulate pen behaviour:

```
EVENT type 15 (RawButtonPress)
    device: 2 (16)
    detail: 1
    flags: 
    valuators:

--------- numerous EVENT type 17 (RawMotion) events ----------

EVENT type 16 (RawButtonRelease)
    device: 2 (16)
    detail: 1
    flags: 
    valuators:
```

A pen vertically dropped some centimeters onto the tablet surface with the hand kept at a distance to minimise any disturbances yielded the following results:

```
EVENT type 15 (RawButtonPress)
    device: 2 (8)
    detail: 1
    flags: 
    valuators:
          0: 16324.00 (16324.00)
          1: 15667.00 (15667.00)
          2: 42964.00 (42964.00)
          3: 0.00 (0.00)
          4: 4.00 (4.00)
          5: -900.00 (-900.00)


--------- numerous EVENT type 17 (RawMotion) events ----------


EVENT type 16 (RawButtonRelease)
    device: 2 (8)
    detail: 1
    flags: 
    valuators:
          0: 15986.00 (15986.00)
          1: 15339.00 (15339.00)
          2: 0.00 (0.00)
          3: 0.00 (0.00)
          4: 2.00 (2.00)
          5: -900.00 (-900.00)
```

Could it be that whatever you use to get mouse events has problems handling these valuators that come with the button events?

**Comment by Braintoe** [comment]
Small update to the commente above: I overlooked that I just copied the "Raw" events, sorry. In all cases above, there are also ButtonPress/Release events:

Pen:
```
EVENT type 15 (RawButtonPress)
    device: 2 (8)
    detail: 1
    flags: 
    valuators:
          0: 28385.00 (28385.00)
          1: 4290.00 (4290.00)
          2: 20457.00 (20457.00)
          3: 20.00 (20.00)
          4: 26.00 (26.00)
          5: -900.00 (-900.00)

EVENT type 4 (ButtonPress)
    device: 8 (8)
    detail: 1
    flags: 
    root: 2438.17/221.09
    event: 100.17/81.09
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
        0: 28385.00
        1: 4290.00
        2: 20457.00
        3: 20.00
        4: 26.00
        5: -900.00
    windows: root 0x1e0 event 0x7400001 child 0x0

EVENT type 9 (FocusIn)
    device: 3 (3)
    windows: root 0x1e0 event 0x7400001 child 0x0
    mode: NotifyNormal (detail NotifyNonlinear)
    flags:  [same screen]
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    root x/y:  2438.00 / 221.00
    event x/y: 100.00 / 81.00

EVENT type 4 (ButtonPress)
    device: 2 (8)
    detail: 1
    flags: 
    root: 2438.17/221.09
    event: 100.17/81.09
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
        0: 28385.00
        1: 4290.00
        2: 20457.00
        3: 20.00
        4: 26.00
        5: -900.00
    windows: root 0x1e0 event 0x7400001 child 0x0

EVENT type 17 (RawMotion)
    device: 2 (8)
    detail: 0
    flags: 
    valuators:
          0: 28382.00 (28382.00)
          1: 4289.00 (4289.00)
          2: 27405.00 (27405.00)
          3: 19.00 (19.00)
          4: 26.00 (26.00)
          5: -900.00 (-900.00)

EVENT type 6 (Motion)
    device: 8 (8)
    detail: 0
    flags: 
    root: 2438.91/221.04
    event: 100.91/81.04
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
        0: 28382.00
        1: 4289.00
        2: 27405.00
        3: 19.00
        4: 26.00
        5: -900.00
    windows: root 0x1e0 event 0x7400001 child 0x0

EVENT type 8 (Leave)
    device: 2 (8)
    windows: root 0x1e0 event 0x7400001 child 0x0
    mode: NotifyNormal (detail NotifyInferior)
    flags: [focus] [same screen]
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    root x/y:  2437.00 / 221.00
    event x/y: 99.00 / 81.00

EVENT type 7 (Enter)
    device: 2 (8)
    windows: root 0x1e0 event 0x7400002 child 0x0
    mode: NotifyNormal (detail NotifyAncestor)
    flags: [focus] [same screen]
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    root x/y:  2437.00 / 221.00
    event x/y: 49.00 / 31.00


------- Numerous events of Types EVENT type 6 (Motion) and EVENT type 17 (RawMotion) in between here -------


EVENT type 16 (RawButtonRelease)
    device: 2 (8)
    detail: 1
    flags: 
    valuators:
          0: 28359.00 (28359.00)
          1: 4255.00 (4255.00)
          2: 0.00 (0.00)
          3: 16.00 (16.00)
          4: 28.00 (28.00)
          5: -900.00 (-900.00)

EVENT type 5 (ButtonRelease)
    device: 8 (8)
    detail: 1
    flags: 
    root: 2435.94/219.29
    event: 97.94/79.29
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
        0: 28359.00
        1: 4255.00
        2: 0.00
        3: 16.00
        4: 28.00
        5: -900.00
    windows: root 0x1e0 event 0x7400001 child 0x7400002

EVENT type 5 (ButtonRelease)
    device: 2 (8)
    detail: 1
    flags: 
    root: 2435.94/219.29
    event: 97.94/79.29
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
        0: 28359.00
        1: 4255.00
        2: 0.00
        3: 16.00
        4: 28.00
        5: -900.00
    windows: root 0x1e0 event 0x7400001 child 0x7400002

EVENT type 8 (Leave)
    device: 2 (2)
    windows: root 0x1e0 event 0x7400001 child 0x0
    mode: NotifyUngrab (detail NotifyInferior)
    flags: [focus] [same screen]
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    root x/y:  2435.00 / 219.00
    event x/y: 97.00 / 79.00
```


Finger touching tablet:
```
EVENT type 15 (RawButtonPress)
    device: 2 (10)
    detail: 1
    flags: 
    valuators:

EVENT type 4 (ButtonPress)
    device: 10 (10)
    detail: 1
    flags: 
    root: 134.63/220.88
    event: 84.63/89.88
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x1e0 event 0x7400001 child 0x7400002
EVENT type 7 (Enter)
    device: 2 (2)
    windows: root 0x1e0 event 0x7400001 child 0x0
    mode: NotifyGrab (detail NotifyInferior)
    flags:  [same screen]
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    root x/y:  134.00 / 220.00
    event x/y: 84.00 / 89.00
EVENT type 9 (FocusIn)
    device: 3 (3)
    windows: root 0x1e0 event 0x7400001 child 0x0
    mode: NotifyNormal (detail NotifyNonlinear)
    flags:  [same screen]
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    root x/y:  134.00 / 220.00
    event x/y: 84.00 / 89.00
EVENT type 8 (Leave)
    device: 2 (2)
    windows: root 0x1e0 event 0x7400001 child 0x0
    mode: NotifyUngrab (detail NotifyInferior)
    flags: [focus] [same screen]
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    root x/y:  134.00 / 220.00
    event x/y: 84.00 / 89.00
EVENT type 4 (ButtonPress)
    device: 2 (10)
    detail: 1
    flags: 
    root: 134.63/220.88
    event: 84.63/89.88
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x1e0 event 0x7400001 child 0x7400002
EVENT type 7 (Enter)
    device: 2 (2)
    windows: root 0x1e0 event 0x7400001 child 0x0
    mode: NotifyGrab (detail NotifyInferior)
    flags: [focus] [same screen]
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    root x/y:  134.00 / 220.00
    event x/y: 84.00 / 89.00
EVENT type 16 (RawButtonRelease)
    device: 2 (10)
    detail: 1
    flags: 
    valuators:

EVENT type 5 (ButtonRelease)
    device: 10 (10)
    detail: 1
    flags: 
    root: 134.63/220.88
    event: 84.63/89.88
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x1e0 event 0x7400001 child 0x7400002
EVENT type 5 (ButtonRelease)
    device: 2 (10)
    detail: 1
    flags: 
    root: 134.63/220.88
    event: 84.63/89.88
    buttons: 1
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x1e0 event 0x7400001 child 0x7400002
EVENT type 8 (Leave)
    device: 2 (2)
    windows: root 0x1e0 event 0x7400001 child 0x0
    mode: NotifyUngrab (detail NotifyInferior)
    flags: [focus] [same screen]
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    root x/y:  134.00 / 220.00
    event x/y: 84.00 / 89.00
```

Again, the valutators are the only obvious difference for these events unless I overlook something. While most problems handle these events just normal, Cura and Teamviewer do not.
